package web

import "embed"

// DistFS contains the production frontend generated by `pnpm run build`.
// Keeping the filesystem in this package lets the Go server embed the same
// artifact that the Makefile builds, without duplicating frontend assets.
//
//go:embed dist/*
var DistFS embed.FS
